CREATE TABLE COUNTRY (
    cid NUMBER,
    cname VARCHAR2(50),
    PRIMARY KEY (cid)
);

-- Initialize COUNTRY table data
INSERT INTO COUNTRY (CID,CNAME) VALUES ('1','Andorra');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('2','United Arab Emirates');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('3','Afghanistan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('4','Antigua and Barbuda');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('5','Anguilla');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('6','Albania');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('7','Armenia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('8','Netherlands Antilles');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('9','Angola');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('10','Antarctica');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('11','Argentina');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('12','American Samoa');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('13','Austria');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('14','Australia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('15','Aruba');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('16','Åland Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('17','Azerbaijan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('18','Bosnia and Herzegovina');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('19','Barbados');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('20','Bangladesh');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('21','Belgium');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('22','Burkina Faso');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('23','Bulgaria');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('24','Bahrain');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('25','Burundi');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('26','Benin');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('27','Saint Barthélemy');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('28','Bermuda');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('29','Brunei');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('30','Bolivia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('31','Bonaire, Sint Eustatius and Saba');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('32','Brazil');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('33','Bahamas');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('34','Bhutan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('35','Bouvet Island');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('36','Botswana');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('37','Belarus');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('38','Belize');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('39','Canada');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('40','Cocos Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('41','The Democratic Republic Of Congo');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('42','Central African Republic');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('43','Congo');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('44','Switzerland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('45','Côte d''Ivoire');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('46','Cook Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('47','Chile');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('48','Cameroon');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('49','China');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('50','Colombia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('51','Costa Rica');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('52','Cuba');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('53','Cape Verde');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('54','Curaçao');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('55','Christmas Island');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('56','Cyprus');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('57','Czech Republic');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('58','Germany');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('59','Djibouti');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('60','Denmark');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('61','Dominica');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('62','Dominican Republic');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('63','Algeria');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('64','Ecuador');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('65','Estonia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('66','Egypt');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('67','Western Sahara');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('68','Eritrea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('69','Spain');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('70','Ethiopia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('71','Finland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('72','Fiji');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('73','Falkland Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('74','Micronesia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('75','Faroe Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('76','France');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('77','Gabon');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('78','United Kingdom');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('79','Grenada');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('80','Georgia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('81','French Guiana');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('82','Guernsey');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('83','Ghana');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('84','Gibraltar');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('85','Greenland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('86','Gambia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('87','Guinea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('88','Guadeloupe');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('89','Equatorial Guinea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('90','Greece');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('91','South Georgia And The South Sandwich Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('92','Guatemala');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('93','Guam');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('94','Guinea-Bissau');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('95','Guyana');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('96','Hong Kong');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('97','Heard Island And McDonald Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('98','Honduras');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('99','Croatia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('100','Haiti');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('101','Hungary');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('102','Indonesia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('103','Ireland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('104','Israel');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('105','Isle Of Man');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('106','India');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('107','British Indian Ocean Territory');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('108','Iraq');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('109','Iran');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('110','Iceland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('111','Italy');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('112','Jersey');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('113','Jamaica');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('114','Jordan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('115','Japan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('116','Kenya');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('117','Kyrgyzstan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('118','Cambodia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('119','Kiribati');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('120','Comoros');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('121','Saint Kitts And Nevis');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('122','North Korea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('123','South Korea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('124','Kuwait');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('125','Cayman Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('126','Kazakhstan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('127','Laos');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('128','Lebanon');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('129','Saint Lucia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('130','Liechtenstein');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('131','Sri Lanka');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('132','Liberia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('133','Lesotho');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('134','Lithuania');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('135','Luxembourg');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('136','Latvia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('137','Libya');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('138','Morocco');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('139','Monaco');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('140','Moldova');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('141','Montenegro');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('142','Saint Martin');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('143','Madagascar');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('144','Marshall Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('145','Macedonia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('146','Mali');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('147','Myanmar');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('148','Mongolia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('149','Macao');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('150','Northern Mariana Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('151','Martinique');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('152','Mauritania');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('153','Montserrat');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('154','Malta');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('155','Mauritius');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('156','Maldives');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('157','Malawi');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('158','Mexico');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('159','Malaysia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('160','Mozambique');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('161','Namibia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('162','New Caledonia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('163','Niger');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('164','Norfolk Island');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('165','Nigeria');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('166','Nicaragua');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('167','Netherlands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('168','Norway');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('169','Nepal');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('170','Nauru');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('171','Niue');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('172','New Zealand');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('173','Oman');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('174','Panama');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('175','Peru');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('176','French Polynesia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('177','Papua New Guinea');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('178','Philippines');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('179','Pakistan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('180','Poland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('181','Saint Pierre And Miquelon');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('182','Pitcairn');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('183','Puerto Rico');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('184','Palestine');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('185','Portugal');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('186','Palau');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('187','Paraguay');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('188','Qatar');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('189','Reunion');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('190','Romania');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('191','Serbia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('192','Russia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('193','Rwanda');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('194','Saudi Arabia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('195','Solomon Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('196','Seychelles');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('197','Sudan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('198','Sweden');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('199','Singapore');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('200','Saint Helena');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('201','Slovenia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('202','Svalbard And Jan Mayen');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('203','Slovakia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('204','Sierra Leone');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('205','San Marino');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('206','Senegal');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('207','Somalia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('208','Suriname');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('209','South Sudan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('210','Sao Tome And Principe');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('211','El Salvador');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('212','Sint Maarten (Dutch part)');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('213','Syria');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('214','Swaziland');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('215','Turks And Caicos Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('216','Chad');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('217','French Southern Territories');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('218','Togo');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('219','Thailand');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('220','Tajikistan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('221','Tokelau');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('222','Timor-Leste');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('223','Turkmenistan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('224','Tunisia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('225','Tonga');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('226','Turkey');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('227','Trinidad and Tobago');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('228','Tuvalu');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('229','Taiwan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('230','Tanzania');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('231','Ukraine');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('232','Uganda');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('233','United States Minor Outlying Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('234','United States');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('235','Uruguay');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('236','Uzbekistan');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('237','Vatican');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('238','Saint Vincent And The Grenadines');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('239','Venezuela');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('240','British Virgin Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('241','U.S. Virgin Islands');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('242','Vietnam');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('243','Vanuatu');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('244','Wallis And Futuna');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('245','Samoa');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('246','Yemen');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('247','Mayotte');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('248','South Africa');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('249','Zambia');
INSERT INTO COUNTRY (CID,CNAME) VALUES ('250','Zimbabwe');


CREATE TABLE STATS(
    countryID NUMBER,
    totalTest NUMBER,
    totalCase NUMBER,
    totalIntubated NUMBER,
    totalICU NUMBER,
    totalRecovered NUMBER,
    totalDeceased NUMBER,
    PRIMARY KEY (countryID),
    FOREIGN KEY (countryID) REFERENCES COUNTRY(cid)
);


-- Initialize statistics for each country to zeros.
INSERT INTO STATS SELECT cid AS countryID, 0, 0, 0, 0, 0, 0  FROM COUNTRY;

CREATE TABLE ROLES (
    rid NUMBER,
    rname VARCHAR2(25),
    PRIMARY KEY (rid)
);

-- Insert admin and user roles
INSERT INTO ROLES(rid, rname) VALUES(1, 'admin');
INSERT INTO ROLES(rid, rname) VALUES(2, 'user');


CREATE TABLE USERS (
    id VARCHAR2(50),
    pass VARCHAR2(11),
    fName VARCHAR2(25),
    lName VARCHAR2(25),
    rid NUMBER,
    countryID NUMBER, 
    PRIMARY KEY(id),
    FOREIGN KEY(rid) REFERENCES ROLES(rid),
    FOREIGN KEY(countryID) REFERENCES COUNTRY (cid)
);

-- Insert "admin" user with password as "admin", role as "admin" and country as "Turkey"
INSERT INTO USERS(id, pass, fName, lName, rid, countryID) VALUES('admin', 'admin', 'Emre', 'Kardaslar', 1, 226);

CREATE TABLE CVDATA (
    countryID NUMBER,
    day DATE,
    numTest NUMBER,
    numCase NUMBER,
    numIntubated NUMBER,
    numICU NUMBER,
    numRecovered NUMBER,
    numDeceased NUMBER,
    PRIMARY KEY (countryID,day),
    FOREIGN KEY (countryID) REFERENCES COUNTRY(cid)
);

-- Create AFTER INSERT, AFTER DELETE and AFTER UPDATE triggers on CVDATA table to maintain statistics data.

CREATE OR REPLACE TRIGGER cvdata_after_insert  
AFTER INSERT  
   ON CVDATA  
   FOR EACH ROW  
BEGIN  
   UPDATE STATS SET  
   	totalTest = totalTest + :new.numTest,  
   	totalCase = totalCase + :new.numCase,  
       totalIntubated = totalIntubated + :new.numIntubated, 
       totalICU = totalICU + :new.numICU, 
       totalRecovered = totalRecovered + :new.numRecovered, 
       totalDeceased = totalDeceased + :new.numDeceased  
 WHERE countryID = :new.countryID; 
END;
/

CREATE OR REPLACE TRIGGER cvdata_after_delete  
AFTER DELETE  
   ON CVDATA  
   FOR EACH ROW  
BEGIN  
   UPDATE STATS SET  
   	totalTest = totalTest - :old.numTest,  
   	totalCase = totalCase - :old.numCase,  
       totalIntubated = totalIntubated - :old.numIntubated, 
       totalICU = totalICU - :old.numICU, 
       totalRecovered = totalRecovered - :old.numRecovered, 
       totalDeceased = totalDeceased - :old.numDeceased  
 WHERE countryID = :old.countryID; 
END;
/

CREATE OR REPLACE TRIGGER cvdata_after_update  
AFTER UPDATE  
   ON CVDATA  
   FOR EACH ROW  
BEGIN  	
   UPDATE STATS SET  
   	totalTest = totalTest + :new.numTest,  
   	totalCase = totalCase + :new.numCase,  
       totalIntubated = totalIntubated + :new.numIntubated, 
       totalICU = totalICU + :new.numICU, 
       totalRecovered = totalRecovered + :new.numRecovered, 
       totalDeceased = totalDeceased + :new.numDeceased  
 WHERE countryID = :new.countryID; 

   UPDATE STATS SET  
   	totalTest = totalTest - :old.numTest,  
   	totalCase = totalCase - :old.numCase,  
       totalIntubated = totalIntubated - :old.numIntubated, 
       totalICU = totalICU - :old.numICU, 
       totalRecovered = totalRecovered - :old.numRecovered, 
       totalDeceased = totalDeceased - :old.numDeceased  
 WHERE countryID = :old.countryID; 
END;
/

